import 'dotenv/config';import express from 'express';import cors from 'cors';import bcrypt from 'bcryptjs';import jwt from 'jsonwebtoken';import multer from 'multer';import fs from 'node:fs';import crypto from 'node:crypto';import path from 'node:path';import {db} from './db.js';
const app=express(),port=Number(process.env.PORT||8787),secret=process.env.JWT_SECRET||'dev-secret-change-me';const origins=(process.env.CORS_ORIGIN||'*').split(',');app.use(cors({origin:(o,cb)=>cb(null,!o||origins.includes('*')||origins.includes(o))}));app.use(express.json({limit:'2mb'}));const uploadDir=process.env.UPLOAD_DIR||'./uploads';fs.mkdirSync(uploadDir,{recursive:true});const upload=multer({dest:uploadDir,limits:{fileSize:50*1024*1024}});
const tokenFor=u=>jwt.sign({id:u.id,email:u.email,displayName:u.display_name},secret,{expiresIn:'30d'});function auth(req,res,next){const h=req.headers.authorization||'';try{req.user=jwt.verify(h.replace(/^Bearer\s+/,'').trim(),secret);next()}catch{return res.status(401).json({message:'Unauthorized'})}}
app.get('/api/health',(req,res)=>res.json({ok:true,service:'ks-steam-api',version:'4.2.0'}));
app.post('/api/auth/register',async(req,res)=>{const email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||''),displayName=String(req.body.displayName||'KS User').trim();if(!email||password.length<8)return res.status(400).json({message:'Valid email and password (8+ chars) required'});try{const hash=await bcrypt.hash(password,12);const now=new Date().toISOString();const r=db.prepare('INSERT INTO users(email,password_hash,display_name,created_at) VALUES(?,?,?,?)').run(email,hash,displayName,now);const u=db.prepare('SELECT id,email,display_name FROM users WHERE id=?').get(r.lastInsertRowid);res.status(201).json({token:tokenFor(u),user:u})}catch(e){res.status(409).json({message:'Email already registered'})}});
app.post('/api/auth/login',async(req,res)=>{const email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||'');const u=db.prepare('SELECT * FROM users WHERE email=?').get(email);if(!u||!(await bcrypt.compare(password,u.password_hash)))return res.status(401).json({message:'Invalid credentials'});res.json({token:tokenFor(u),user:{id:u.id,email:u.email,display_name:u.display_name}})});
app.get('/api/me',auth,(req,res)=>res.json({user:req.user}));
app.get('/api/releases',(req,res)=>{const limit=Math.min(Number(req.query.limit)||50,100);const rows=db.prepare('SELECT id,name,slug,description,category,license,created_at,updated_at FROM releases ORDER BY updated_at DESC LIMIT ?').all(limit);res.json({items:rows})});
app.get('/api/releases/:id',(req,res)=>{const r=db.prepare('SELECT * FROM releases WHERE id=? OR slug=?').get(req.params.id,req.params.id);if(!r)return res.status(404).json({message:'Release not found'});const versions=db.prepare('SELECT * FROM versions WHERE release_id=? ORDER BY created_at DESC').all(r.id);for(const v of versions)v.sources=db.prepare('SELECT type,url,label FROM sources WHERE version_id=?').all(v.id);r.versions=versions;r.screenshots=db.prepare('SELECT url,alt FROM screenshots WHERE release_id=?').all(r.id);r.reviews=db.prepare('SELECT reviews.rating,reviews.body,reviews.created_at,users.display_name FROM reviews JOIN users ON users.id=reviews.user_id WHERE release_id=? ORDER BY reviews.created_at DESC').all(r.id);res.json(r)});
app.post('/api/releases',auth,(req,res)=>{const b=req.body;const id=String(b.id||crypto.randomUUID()),slug=String(b.slug||b.name||id).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');const now=new Date().toISOString();db.prepare('INSERT INTO releases(id,name,slug,description,category,license,owner_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').run(id,b.name,b.description,b.category,b.license||'',req.user.id,now,now);res.status(201).json({id,slug})});
app.post('/api/releases/:id/versions',auth,(req,res)=>{const r=db.prepare('SELECT * FROM releases WHERE id=?').get(req.params.id);if(!r||r.owner_id!==req.user.id)return res.status(403).json({message:'Not allowed'});const now=new Date().toISOString();const v=db.prepare('INSERT INTO versions(release_id,version,notes,created_at) VALUES(?,?,?,?)').run(r.id,String(req.body.version),String(req.body.notes||''),now);for(const s of req.body.sources||[])db.prepare('INSERT INTO sources(version_id,type,url,label) VALUES(?,?,?,?)').run(v.lastInsertRowid,s.type,s.url,s.label||null);db.prepare('UPDATE releases SET updated_at=? WHERE id=?').run(now,r.id);res.status(201).json({id:v.lastInsertRowid})});
app.post('/api/releases/:id/screenshots',auth,upload.array('screenshots',8),(req,res)=>{const r=db.prepare('SELECT * FROM releases WHERE id=?').get(req.params.id);if(!r||r.owner_id!==req.user.id)return res.status(403).json({message:'Not allowed'});const base=`/uploads`;const out=[];for(const f of req.files||[]){const url=`${base}/${path.basename(f.path)}`;db.prepare('INSERT INTO screenshots(release_id,url,alt) VALUES(?,?,?)').run(r.id,url,String(req.body.alt||''));out.push(url)}res.status(201).json({screenshots:out})});
app.post('/api/releases/:id/reviews',auth,(req,res)=>{const rating=Number(req.body.rating),body=String(req.body.body||'').trim();if(![1,2,3,4,5].includes(rating)||!body)return res.status(400).json({message:'Rating 1-5 and review text required'});const r=db.prepare('SELECT id FROM releases WHERE id=?').get(req.params.id);if(!r)return res.status(404).json({message:'Release not found'});db.prepare('INSERT INTO reviews(release_id,user_id,rating,body,created_at) VALUES(?,?,?,?,?)').run(r.id,req.user.id,rating,body,new Date().toISOString());res.status(201).json({ok:true})});
app.post('/api/client/sync',auth,(req,res)=>{const b=req.body||{},now=new Date().toISOString();db.prepare('INSERT INTO client_devices(user_id,name,version,platform,last_seen) VALUES(?,?,?,?,?)').run(req.user.id,String(b.name||'KS Steam Client'),String(b.version||''),String(b.platform||''),now);const releases=db.prepare('SELECT id,name,slug,updated_at FROM releases ORDER BY updated_at DESC').all();res.json({serverTime:now,catalogVersion:'4.2',releases})});
app.use('/uploads',express.static(uploadDir));app.listen(port,()=>console.log(`KS Steam API listening on http://localhost:${port}`));
